### PR TITLE
Android smoke tests

### LINKED ISSUE #119: Add android smoke tests
Currently android uses it's own kotlin `Core.kt` to negotiate the core lib.

Even though it looks like it might, it doesn't check that contract is fulfilled at compile time.

(I'm pretty sure) it doesn't even check at `System.loadLib` time.

It only checks when a specific function is invoked, and then if it fails it fails at runtime.

Add a series of "SmokeTests" one for each `external func`. They don't need to succeed from the rust point of view (it's okay if they return an integer that signals error) because that means it found and ran the function.

### PR DESCRIPTION
**Pull request by SmailBarkouch**
Added tests for each endpoint in kotlin (close #119 )
Added kotlin-interface-tests github actions with its respective docker components
Added a way to view logs in android (you are required to be in debuging mode to view it in settings)
Optimized android docker and android code

### CODE REVIEW

File: clients/android/app/src/test/java/app/lockbook/ExecuteWorkTest.kt [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+        coreModel.insertFile(document).component1()!!
+        val folder =
+            coreModel.createFile(generateAlphaString(), Klaxon().toJsonString(FileType.Folder))
+                .component1()!!
+        coreModel.insertFile(folder).component1()!!
+        val syncWork = coreModel.calculateFileSyncWork().component1()!!
+        for (workUnit in syncWork.work_units) {
+            coreModel.executeFileSyncWork(coreModel.getAccount().component1()!!, workUnit)
+                .component1()!!
+        }
```
Comment (Parth) [inline clients/android/app/src/test/java/app/lockbook/ExecuteWorkTest.kt:54]: Should this test not require something?

File: clients/android/app/src/test/java/app/lockbook/GetAccountTest.kt [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+    @After
+    fun resetDirectory() {
+        Runtime.getRuntime().exec("rm -rf $path")
+    }
+
+    @Test
+    fun getAccountOk() {
+        val coreModel = CoreModel(Config(path))
+        CoreModel.generateAccount(Config(path), generateAlphaString()).component1()!!
+        coreModel.getAccount().component1()!!
```
Comment (Parth) [inline clients/android/app/src/test/java/app/lockbook/GetAccountTest.kt:38]: Shouldn't this `require` something

File: containers/Dockerfile.kotlin_tests [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+ENV DEBIAN_FRONTEND=noninteractive
+ENV ANDROID_HOME /opt/android-sdk-linux
+RUN apt update && apt install -y build-essential openjdk-8-jdk wget curl unzip
+
+# Install rust things
+RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
+ENV PATH="/root/.cargo/bin:${PATH}"
+
+# Install android things
+RUN wget -q https://dl.google.com/android/repository/android-ndk-r21c-linux-x86_64.zip -O android-ndk-r21c-linux-x86_64.zip
```
Comment (Parth) [inline containers/Dockerfile.kotlin_tests:11]: You don't need to install android things

File: core/Makefile [hunk 4]
```diff
@@ -6,11 +6,13 @@ android:
...
-	@rm -rf $(jniLibs)
+	@rm -rf $(jniLibs)/arm64-v8a
+	@rm -rf $(jniLibs)/armebi-v7a
+	@rm -rf $(jniLibs)/x86
+	@rm -rf $(jniLibs)/x86_64
 
 	@echo "Moving new .so's over"
-	@mkdir $(jniLibs)
-	@mkdir $(jniLibs)/arm64-v8a
+	@mkdir -p $(jniLibs)/arm64-v8a
```
Comment (Parth) [inline core/Makefile:15]: explain this change?

File: core/Makefile [hunk 5]
```diff
@@ -20,6 +22,45 @@ android:
...
+	@touch src/lib.rs
+	@cargo build --lib --release
+	
+	@echo "Cleaning up old .dylib if they exist"
+	@rm -rf $(jniLibs)/desktop
+	
+	@echo "Moving new .dylib over"
+	@mkdir -p $(jniLibs)/desktop
+
+	@mv target/release/$(macosLibName) $(jniLibs)/desktop/$(macosLibName)
```
Comment (Parth) [inline core/Makefile:36]: Any reason you prefer `mv` over `cp`? Still thinking about which I like more

**Comment by Parth** [comment]
Closes #119

File: core/Makefile (hunk 5 above)
Comment (SmailBarkouch) [reply core/Makefile:36]: I use mv since I can take that library and not have cargo rebuild everything the next time I call the command. So I just thought I might as well just take it rather than copy it over.

File: core/Makefile (hunk 4 above)
Comment (SmailBarkouch) [reply core/Makefile:15]: The -p means it will create the sub directories of the folder you are trying to create if they don't already exist. So I can replace those two commands with just that.

File: core/Makefile (hunk 5 above)
Comment (raayan) [reply core/Makefile:36]: I imagine `mv` would make cargo rebuild since the target folder has been modified

File: core/Makefile (hunk 4 above)
Comment (raayan) [reply core/Makefile:15]: `-p` is good for things like this

**Comment by Parth** [comment]
This should fix #189 as well
