### PR TITLE
android, core: fix search crashes

### LINKED ISSUE #1293: searching crashes core
Searching from android for some folder names will sometimes cause core to crash.

### PR DESCRIPTION
**Pull request by SmailBarkouch**
Search was crashing on android. The problem ended up being with the content window being miss-computed, and thus the matched indices were false. Sometimes, the matched indices would be larger than the content window, thus giving an out of bounds error.

The crash happened in android, but it was caused by core.

fixes #1293

### CODE REVIEW

File: core/src/service/search_service.rs [hunk 1]
```diff
@@ -372,7 +372,7 @@ impl RequestContext<'_, '_> {
                 let take_chars_len = if at_least_take > IDEAL_CONTENT_MATCH_LENGTH {
                     at_least_take
                 } else {
-                    IDEAL_CONTENT_MATCH_LENGTH - (last_match - index_offset)
+                    IDEAL_CONTENT_MATCH_LENGTH
```
Comment (Parth) [inline core/src/service/search_service.rs:375]: you found a flaw in your logic, what you really found is a missing test case

**Review by Parth — CHANGES_REQUESTED** [review]

**Review by Parth — APPROVED** [review]
