### PR TITLE
canvas: pen tool bug where new path connects to old path  

### LINKED ISSUE #2342: when ending and beginning a touch in a drawing, the old stroke will connect to the new one

### PR DESCRIPTION
**Pull request by ad-tra**
when implementing some functionalities of Canvas, I've always assumed that if the window is in focus, there's a cursor with a hover position. this assumption is wrong for touch screens because when the user is not pressing or touching there's no hover cursor.  

This PR re-evaluates the assumption and fixes bugs for both pen and eraser tools.  
- pen (fixes #2342)
- eraser: there was an issue where if you erase paths, they would just turn gray but they would stay on the screen. It's now fixed.

### CODE REVIEW

**Comment by smailbarkouch** [comment]
I still am experiencing the issue on iOS.

**Review by smailbarkouch — CHANGES_REQUESTED** [review]
I am still experiencing the issue on iOS.

File: libs/content/workspace/src/tab/svg_editor/selection.rs [hunk 1]
```diff
@@ -90,6 +90,7 @@ impl Selection {
                     } else {
                         self.selected_elements = vec![new_selected_el]
                     }
+                    self.current_op = SelectionOperation::Drag;
```
Comment (ad-tra) [inline libs/content/workspace/src/tab/svg_editor/selection.rs:93]: this is unrelated to this PR, but i noticed a small bug for the selection module when doing QA.
the bug is that when you press on the edge of an un-selected path you go directly into resize instead of grab mode.

**Review by smailbarkouch — APPROVED** [review]
