### PR TITLE
linux: gtk is initialized before settings and lbcore

### LINKED ISSUE #703: If an error occurs before the gtk application has been initiated, it will crash
If at start up, an error happens due to the settings, or core cannot be initialized, it will attempt to create a dialog. But since the GTK application has not been initiated, it will crash.

```
thread 'main' panicked at 'GTK has not been initialized. Call `gtk::init` first.', 
```

Note, this may be tied to debian crashes.

### PR DESCRIPTION
**Pull request by SmailBarkouch**
If an error occurred while initializing `Settings` or `LbCore`, we call `launch_err` to post a dialog for this error. The problem is, you can't post a dialog if gtk+ is not initialized, and we initialize gtk+ on the very last line of the main function with `gtk_app.run(&[])`. So if an error happens, it will crash when attempting to run the dialog. So `gtk::init().unwrap()` has been added so we can successfully run dialogs before the `GtkApp` itself is run.

fixes #703

### CODE REVIEW

**Review by Parth — APPROVED** [review]

File: clients/linux/src/main.rs [hunk 1]
```diff
@@ -38,6 +38,7 @@ use crate::settings::Settings;
 
 fn main() {
     let data_dir = get_data_dir();
+    gtk::init().unwrap();
```
Comment (steverusso) [inline clients/linux/src/main.rs:41]: Just make this the first line then followed by a blank line.

**Review by steverusso — CHANGES_REQUESTED** [review]

**Review by steverusso — APPROVED** [review]
