### PR TITLE
canvas: fix stroke connecting on non touch screens

### LINKED ISSUE #2858: canvas connects stroke when drawing with a mouse
https://github.com/user-attachments/assets/a05bbcdb-c3e7-4486-ae38-a329c7eb0b13

### PR DESCRIPTION
**Pull request by ad-tra**
fixes #2858 and maybe #2857

### CODE REVIEW

File: libs/content/workspace/src/tab/svg_editor/pen.rs [hunk 1]
```diff
@@ -151,10 +112,10 @@ impl Pen {
...
                     }
 
-                    if self.detect_snap(&p.data, payload.pos, pen_ctx.buffer.master_transform) {
-                        self.end_path(pen_ctx, true);
-                        return;
-                    }
+                    // if self.detect_snap(&p.data, payload.pos, pen_ctx.buffer.master_transform) {
+                    //     self.end_path(pen_ctx, true);
+                    //     return;
+                    // }
```
Comment (Parth) [inline libs/content/workspace/src/tab/svg_editor/pen.rs:118]: ?

**Review by Parth — CHANGES_REQUESTED** [review]
same as other PR

File: libs/content/workspace/src/tab/svg_editor/pen.rs (hunk 1 above)
Comment (ad-tra) [reply libs/content/workspace/src/tab/svg_editor/pen.rs]: snap is broken and i'm not interested in supporting it until the pen tool is in a stable place which is after i add predicted/coeleased touch support and native svg thickness. the comment serve as a note to myself, I've put a todo comment to make it more clear
