### PR TITLE
android: fixed android crashes from egui drawings

### LINKED ISSUE #1359: bug: drawings created in egui are causing problems on android
1. Simply creating a drawing in egui client and opening on android causes a blank gray screen (no black canvas as far as I can tell).
2. If you _swipe_ in any way on this gray screen and then press the back button, the android client crashes.

### PR DESCRIPTION
**Pull request by SmailBarkouch**
fixes #1359

### CODE REVIEW

File: core/libs/shared/src/drawing.rs [hunk 1]
```diff
@@ -11,6 +11,12 @@ pub struct Drawing {
     pub theme: Option<HashMap<ColorAlias, ColorRGB>>,
 }
 
+impl Default for Drawing {
```
Comment (Parth) [inline core/libs/shared/src/drawing.rs:14]: @steverusso why did we do `new` for `Stroke`?

**Review by Parth — APPROVED** [review]
We want to be consistent between `default` / `new` in that file, but other than that lgtm
