### PR TITLE
editor: fix advance word

### LINKED ISSUE #1657: editor crash on double click outside galley range

### LINKED ISSUE #1664: alt right & alt left cause editor to crash

### PR DESCRIPTION
**Pull request by tvanderstad**
fixes #1664
fixes #1657

### CODE REVIEW

File: libs/editor/egui_editor/src/cursor.rs [hunk 1]
```diff
@@ -186,24 +186,23 @@ impl Cursor {
...
         let galley_text = galley.text(buffer);
         let galley_text_range = galley.text_range(segs);
 
         let word_bound_indices_with_words = galley_text.split_word_bound_indices();
         let word_bound_indices = word_bound_indices_with_words
             .clone()
-            .map(|(idx, _)| segs.byte_offset_to_char(DocByteOffset(idx)))
+            .map(|(idx, _)| {
+                segs.byte_offset_to_char(galley.byte_range().start + RelByteOffset(idx))
+            })
```
Comment (tvanderstad) [inline libs/editor/egui_editor/src/cursor.rs:199]: bug was caused by confusion between offsets into galleys vs offsets into document, so I adjusted to work purely in terms of offsets into document

File: libs/editor/egui_editor/src/events.rs [hunk 2]
```diff
@@ -761,21 +761,20 @@ fn calc_modification(
...
                             );
-                            let end_of_word_pos = cursor.pos;
+                            let begin_of_word_pos = cursor.pos;
                             cursor.advance_word(
-                                true,
+                                false,
                                 &buffer.current,
                                 &buffer.current.segs,
                                 galleys,
                             );
```
Comment (tvanderstad) [inline libs/editor/egui_editor/src/events.rs:776]: Preferring the previous word when the double click occurs on a word boundary makes more sense when clicking at the end of a line (select the last word on this line instead of the first word on the next line). Double-clicking on the first character position of a line now selects the last word on the previous line, which is fine for now

**Review by Parth — APPROVED** [review]
