### PR TITLE
ipad: fix focus and shortcuts

### LINKED ISSUE #2383: no automatic keyboard focus when a document is opened
on iPad

### LINKED ISSUE #2390: cannot navigate tabs with shortcuts
on iPad

### PR DESCRIPTION
**Pull request by smailbarkouch**
I exposed the individual key presses that ipad has to workspace, so now all shortcuts work.

fixes #2390 
fixes #2383 

In addition
+ fixes some visibility issues with the toolbar
+ minor refactors

### CODE REVIEW

File: libs/content/editor/egui_editor/src/input/canonical.rs [hunk 1]
```diff
@@ -121,7 +121,7 @@ pub fn calc(
 ) -> Option<Modification> {
     match event {
         Event::Key { key, pressed: true, modifiers, .. }
-            if matches!(key, Key::ArrowUp | Key::ArrowDown) =>
+            if matches!(key, Key::ArrowUp | Key::ArrowDown) && !cfg!(target_os = "ios") =>
```
Comment (Parth) [inline libs/content/editor/egui_editor/src/input/canonical.rs:124]: explain?

**Review by Parth — APPROVED** [review]
Feel free to merge when complete

File: libs/content/editor/egui_editor/src/input/canonical.rs (hunk 1 above)
Comment (smailbarkouch) [reply libs/content/editor/egui_editor/src/input/canonical.rs:124]: Since I pass all key events to egui now, I need to be selective about which ones are processed. UITextInteraction already handles keys like arrow up and arrow down, so I don't need to handle it here.

Comment (Parth) [reply libs/content/editor/egui_editor/src/input/canonical.rs:124]: What's the behavior without this clause? Is it duplicated?

Comment (smailbarkouch) [reply libs/content/editor/egui_editor/src/input/canonical.rs:124]: Yes

Comment (Parth) [reply libs/content/editor/egui_editor/src/input/canonical.rs:124]: okay sgtm then
