### PR TITLE
infra: fix broken aur

### LINKED ISSUE #1537: aur build problem
reported by @mkoloberdin

### LINKED ISSUE #1677: aur distribution problems
```
  -> Creating working copy of lockbook git repo...
Cloning into 'lockbook'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Sources are ready.
==> Making package: lockbook-desktop 0.7.1-1 (Fri 31 Mar 2023 09:06:47 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
lockbook-desktop
/home/parth/.cache/yay/lockbook-desktop/PKGBUILD: line 25: rustup: command not found
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: lockbook-desktop
[parth@archlinux yay-bin]$ 
```

logs from a fresh arch install, will be using VM's to QA this going forward.

### PR DESCRIPTION
**Pull request by Parth**
fixes #1677

### CODE REVIEW

File: utils/releaser/src/linux/desktop.rs [hunk 1]
```diff
@@ -150,13 +149,13 @@ pkgbase = lockbook-desktop
 	pkgver = {version}
 	pkgrel = 1
 	url = https://github.com/lockbook/lockbook
-	arch = x86_64
-	arch = i686
+	arch = any
```
Comment (SmailBarkouch) [inline utils/releaser/src/linux/desktop.rs:152]: Since you made this `any`, you should also add it to the PKGBUILD: `arch=('any')`

**Review by SmailBarkouch — APPROVED** [review]
