### PR TITLE
Android design

### LINKED ISSUE #175: expose new settings
expose settings with preferences androidx library

### LINKED ISSUE #176: make layout folder and styles.xml more clean
Unify the styles and implement them in all layouts, add those that cannot be implemented into a theme (because of their specificity) into dimens.xml

### LINKED ISSUE #192: Long pressing on a file crashes android app

### LINKED ISSUE #193: Get every SyncError:: WorkExecutionError from sync in lib.rs
Current sync all in lib.rs old retrieve the first workexecutionerror it comes into. Make it return every

### PR DESCRIPTION
**Pull request by SmailBarkouch**
Long pressing a file does not crash anymore (close #192 )
Layouts are more clean, unifying themes (close #176 )
Collects all ExecuteWorkErrors in SyncAll (close #193 )
New better looking theme
New settings based off android preferences (close #175 )
Rename crash is now fixed
Added sorting for files

### CODE REVIEW

File: clients/android/app/src/main/java/app/lockbook/loggedin/listfiles/ListFilesActivity.kt [hunk 1]
```diff
@@ -4,39 +4,64 @@ import android.content.Intent
...
+            R.id.menu_settings -> {
                 startActivity(Intent(applicationContext, SettingsActivity::class.java))
                 true
             }
+            R.id.menu_sort -> {
+                val fragment = getFragment().component1()
+                if (fragment is ListFilesFragment) {
+                    fragment.onSortPressed()
+                } else {
+                    Timber.e("Unable to get result of back press.")
```
Comment (Parth) [inline clients/android/app/src/main/java/app/lockbook/loggedin/listfiles/ListFilesActivity.kt:40]: copy paste mistake? back button not pressed?
