### PR TITLE
core: fix many instances of problems related to reading and writing documents 

### LINKED ISSUE #1253: reuse code in document_service
+ import export
+ sync service
+ usage service 
+ integrity_service

all duplicate tricky logic around:
+ filtering out deleted files
+ not trying to read new, uninitialized files
+ decrypting files
+ which sub tree you're interested in

### PR DESCRIPTION
**Pull request by Parth**
Reading and writing documents is tricky business in core. A document may be in `Base` or `Local` depending on whether the user has modified it, it may be deleted. If it's `hmac` is `None` then it may be a new document without any content. 

During the refactor we copied and pasted the document reading code to get going in many places:
+ `document_service` (lib.rs)
+ `search_service`
+ `import_export_service`
+ `usage_service`
+ `drawing_service`

Obviously, bugs followed as complexity grew (sharing), this refactor relocates document reading logic to within the tree. The tree knows whether or not a document should exist on disk, and what it's state should be, how to decrypt it, etc, 

+ [x] now it additionally reads documents from a provided location. 
+ [x] I also simplified the abstractions that existed in `local_storage.rs` which was used more widely pre-hmdb. But now are only used by `document_repo.rs`.
+ [x] Wrote tests that exploit the incorrect logic to validate that bugs exist.
+ [x] Updated all the places to use this new logic. 

fixes #1253

### CODE REVIEW

File: core/libs/shared/src/core_tree.rs [hunk 1]
```diff
@@ -8,6 +8,7 @@ use hmdb::transaction::TransactionTable;
 use std::collections::HashSet;
 use tracing::error;
 use uuid::Uuid;
+extern crate tracing;
```
Comment (steverusso) [inline core/libs/shared/src/core_tree.rs:11]: Shouldn't this appear once in the lib.rs file instead of each file that needs it? Also, does this file even need it?

File: core/libs/shared/src/document_repo.rs [hunk 2]
```diff
@@ -0,0 +1,92 @@
+extern crate tracing;
+
+use crate::core_config::Config;
+use crate::crypto::*;
+use crate::{SharedError, SharedResult};
+use std::fs;
+use std::fs::{create_dir_all, remove_file, File, OpenOptions};
```
Comment (steverusso) [inline core/libs/shared/src/document_repo.rs:7]:
```suggestion
use std::fs::{self, create_dir_all, remove_file, File, OpenOptions};
```

File: core/libs/shared/src/document_repo.rs [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+}
+
+impl RepoSource {
+    fn disk_name(&self) -> &'static str {
+        match &self {
+            RepoSource::Local => "changed_local_documents",
+            RepoSource::Base => "all_base_documents",
+        }
+    }
+}
```
Comment (steverusso) [inline core/libs/shared/src/document_repo.rs:26]:
```suggestion
}

```

File: core/libs/shared/src/document_repo.rs [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+        }
+        Err(err) => match err.kind() {
+            ErrorKind::NotFound => None,
+            _ => return Err(err.into()),
+        },
+    };
+    match maybe_data {
+        None => Ok(None),
+        Some(data) => Ok(bincode::deserialize(&data).map(Some)?),
+    }
```
Comment (steverusso) [inline core/libs/shared/src/document_repo.rs:79]:
```suggestion
    
    Ok(match maybe_data {
        Some(data) => bincode::deserialize(&data).map(Some)?,
        None => None,
    })
```

File: core/libs/test_utils/src/lib.rs [hunk 5]
```diff
@@ -1,12 +1,13 @@
...
-use lockbook_core::model::repo::RepoSource;
 use lockbook_core::repo::schema::OneKey;
-use lockbook_core::repo::{document_repo, local_storage};
-use lockbook_core::{Config, Core};
+use lockbook_core::Core;
 use lockbook_shared::api::{PaymentMethod, StripeAccountTier};
+use lockbook_shared::core_config::Config;
 use lockbook_shared::crypto::EncryptedDocument;
+use lockbook_shared::document_repo;
+use lockbook_shared::document_repo::RepoSource;
```
Comment (steverusso) [inline core/libs/test_utils/src/lib.rs:10]:
```suggestion
use lockbook_shared::document_repo::{self, RepoSource};
```

File: core/libs/test_utils/src/lib.rs [hunk 6]
```diff
@@ -270,37 +271,31 @@ pub fn assert_repo_integrity(core: &Core) {
...
+fn list_files(db: &Config, namespace: &RepoSource) -> Vec<String> {
+    let path = document_repo::namespace_path(db, namespace);
+    let path = Path::new(&path);
 
-    match fs::read_dir(path) {
+    match fs::read_dir(&path) {
         Ok(rd) => {
             let mut file_names = rd
                 .map(|dir_entry| dir_entry.unwrap().file_name().into_string().unwrap())
+                .map(|entry| {
```
Comment (steverusso) [inline core/libs/test_utils/src/lib.rs:290]: No need for two separate, consecutive map calls, right?

File: core/src/lib.rs [hunk 7]
```diff
@@ -41,26 +41,18 @@ use hmdb::log::Reader;
 use hmdb::transaction::Transaction;
 use itertools::Itertools;
 use libsecp256k1::PublicKey;
-use serde::Deserialize;
 use serde_json::{json, value::Value};
 use strum::IntoEnumIterator;
 
 use lockbook_shared::clock;
+pub use lockbook_shared::core_config::Config;
```
Comment (steverusso) [inline core/src/lib.rs:48]: Place with the other `pub use` statements above.

File: core/src/service/sync_service.rs [hunk 8]
```diff
@@ -10,6 +8,8 @@ use lockbook_shared::api::{
     ChangeDocRequest, GetDocRequest, GetUpdatesRequest, GetUpdatesResponse, UpsertRequest,
 };
 use lockbook_shared::core_tree::CoreTree;
+use lockbook_shared::document_repo;
+use lockbook_shared::document_repo::RepoSource;
```
Comment (steverusso) [inline core/src/service/sync_service.rs:12]:
```suggestion
use lockbook_shared::document_repo::{self, RepoSource};
```

File: core/tests/document_tests.rs [hunk 9]
```diff
@@ -1,8 +1,8 @@
 use uuid::Uuid;
 
-use lockbook_core::model::repo::RepoSource;
-use lockbook_core::repo::document_repo;
 use lockbook_shared::crypto::AESEncrypted;
+use lockbook_shared::document_repo;
+use lockbook_shared::document_repo::RepoSource;
```
Comment (steverusso) [inline core/tests/document_tests.rs:5]:
```suggestion
use lockbook_shared::document_repo::{self, RepoSource};
```

File: core/tests/get_usage_tests.rs [hunk 10]
```diff
@@ -1,5 +1,5 @@
-use lockbook_core::model::repo::RepoSource;
-use lockbook_core::repo::document_repo;
+use lockbook_shared::document_repo;
+use lockbook_shared::document_repo::RepoSource;
```
Comment (steverusso) [inline core/tests/get_usage_tests.rs:2]:
```suggestion
use lockbook_shared::document_repo::{self, RepoSource};
```

**Review by steverusso — CHANGES_REQUESTED** [review]

File: core/libs/test_utils/src/lib.rs (hunk 6 above)
Comment (Parth) [reply core/libs/test_utils/src/lib.rs:290]: oh I thought it's conceptually nicer

Comment (steverusso) [reply core/libs/test_utils/src/lib.rs:290]: Imo a single map function is nicer

File: core/libs/shared/src/core_tree.rs (hunk 1 above)
Comment (Parth) [reply core/libs/shared/src/core_tree.rs:11]: not even needed

File: core/libs/test_utils/src/lib.rs (hunk 6 above)
Comment (Parth) [reply core/libs/test_utils/src/lib.rs]: [d4867e9](https://github.com/lockbook/lockbook/pull/1259/commits/d4867e99e6c55765e0c4eceab4dbe9d1bfc68c75)

File: core/libs/shared/src/document_repo.rs [hunk 11]
```diff
@@ -0,0 +1,93 @@
+extern crate tracing;
+
```
Comment (steverusso) [inline core/libs/shared/src/document_repo.rs:2]: I don't think this is necessary though

Comment (Parth) [reply core/libs/shared/src/document_repo.rs]: oops

**Review by steverusso — APPROVED** [review]
