### PR TITLE
core, android: fix move and resolve links in get_children

### LINKED ISSUE #1340: move file dialog doesn't show files on root

### PR DESCRIPTION
**Pull request by SmailBarkouch**
fixes #1340

### CODE REVIEW

File: core/src/service/file_service.rs [hunk 1]
```diff
@@ -171,9 +171,34 @@ impl RequestContext<'_, '_> {
...
+                        children.push(target_file);
+                    }
+                }
+            }
+        }
+
+        for item in &mut children {
+            if let Some(new_parent) = parent_substitutions.get(&item.id) {
+                item.parent = *new_parent;
+            }
```
Comment (Parth) [inline core/src/service/file_service.rs:201]: extract out common code to a fn

**Review by Parth — CHANGES_REQUESTED** [review]

**Review by Parth — APPROVED** [review]
