### PR TITLE
linux: fixed sync crashes and selection is preserved

### LINKED ISSUE #689: If you sync a move it doesn't refresh the file tree

### PR DESCRIPTION
**Pull request by SmailBarkouch**
This bug originated from [this](https://github.com/lockbook/lockbook/pull/737). Whenever the file tree was populated, using the `fill` method from the `FileTree` struct, it triggered the `on_selection_change` closure. This closure is meant to modify the availability of the pop up items (the options that appear when you right click a file) since a new file was selected. But it assumed (using an `.unwrap()`) that there was at least one file in the tree. The problem was, when `fill` is used, the filetree was cleared and added back all its children. Usually this was just called once when the app was opened, which was before the `on_selection_change` closure was added to the tree. Now it was being used while the closure was already there. The fix was to just get rid of the unwrap and allow for an early return.

fixes #689

### CODE REVIEW

File: clients/linux/src/filetree.rs [hunk 1]
```diff
@@ -419,12 +425,16 @@ impl FileTreePopup {
         let tsel = t.get_selection();
         let tmodel = t.get_model().unwrap();
 
+        let is_root = tsel.iter_is_selected(&match tmodel.get_iter_first() {
```
Comment (Parth) [inline clients/linux/src/filetree.rs:428]: you should put this in an `if let` rather than returning early. You can put the rest of this fn in the if let, because that's what's actually happening here

**Review by Parth — CHANGES_REQUESTED** [review]

**Review by Parth — APPROVED** [review]
