### PR TITLE
lb-rs: fix duplicate search results

### LINKED ISSUE #4061: duplicate search results after file updates or deletions
Likely the weirdness that some people (@raayan ?) has been experiencing

### PR DESCRIPTION
**Pull request by smailbarkouch**
Did a few things
1. Added `id_str_raw` with `STRING` type - will be used to remove deleted docs/ids
2. Updated the `Event::MetadataChanged` callback to pass the deleted ids to the `delete` field of `update_tantivy`
3. Updated `build_index` to compute deleted

fixes #4061

### CODE REVIEW

**Comment by Parth** [comment]
> Updated id_str from TEXT to STRING - did this because we don't want to tokenize it

I do want to be able to search via ID

File: libs/lb/lb-rs/src/subscribers/search.rs [hunk 1]
```diff
@@ -189,7 +196,7 @@ impl Lb {
                                 let current_index = lb.search.metadata_index.read().await.clone();
                                 let deleted_ids = replacement_index.compute_deleted(&current_index);
                                 *lb.search.metadata_index.write().await = replacement_index;
-                                lb.update_tantivy(vec![], deleted_ids).await;
+                                lb.update_tantivy(deleted_ids, vec![]).await;
```
Comment (Parth) [inline libs/lb/lb-rs/src/subscribers/search.rs:199]: this is a crazy mistake for me to have made, nice catch

**Comment by Parth** [comment]
> Updated build_index to compute deleted
I don't know if this change is totally needed just because this only happens on startup. There are some obscure situations where we call `build_index` like the CLI, but given the nature of how that gets called it's not needed there either. 

I would remove, but I would not mind if you do not remove, could go either way.

**Review by Parth — CHANGES_REQUESTED** [review]
nice, https://github.com/lockbook/lockbook/pull/4062#issuecomment-3694884411 is the only thing I care about

**Comment by smailbarkouch** [comment]
> > Updated build_index to compute deleted
> > I don't know if this change is totally needed just because this only happens on startup. There are some obscure situations where we call `build_index` like the CLI, but given the nature of how that gets called it's not needed there either.
> 
> I would remove, but I would not mind if you do not remove, could go either way.

Agreed not totally needed - leaning towards leaving it since I would assume `build_index` removes deleted ids

**Comment by smailbarkouch** [comment]
> > Updated id_str from TEXT to STRING - did this because we don't want to tokenize it
> 
> I do want to be able to search via ID

Using `TEXT` makes it impossible (?) to remove the term by ID, since `delete_term` performs an ID lookup and no ID exists as a standalone entry

**Comment by Parth** [comment]
The old code has this:

```rust
        for id in delete {
            let term = Term::from_field_text(id_str, &id.to_string());
            index_writer.delete_term(term);
        }
```

so does this not delete the whole entry? It just clears out that field?

I think having both `id` as text & string is prob fine, it's small. But yeah checkout the docs.

**Comment by smailbarkouch** [comment]
> so does this not delete the whole entry? It just clears out that field?

It doesn't delete anything since id_str is tokenized and it fails to find it

**Comment by Parth** [comment]
I see, unfortunate API design, sounds good best of luck
