### PR TITLE
android: fix an error occured upon opening the app

### LINKED ISSUE #3203: error on startup in android
```
 ZUZ4-11-231 19:3U:59.304988Z DEBUG spawn_build_index: Ib_rs::service::search: close time.busy=24.6μs time.idle=97.9µs 2024-11-23T19:30:59.305008Z DEBUG build_index: lb_rs::service::search: new 2024-11-23T19:30:59.310556Z ERROR build_index: lb_rs::service::search: error=LbErr { kind: AccountNonexistent, backtrace: Some(Backtrace [{fn: "_ZL15_pthread_startPv"}, { fn: "_start_thread" }])} 2024-11-23T19:30:59.390902Z DEBUG build_index: lb_rs::service::search: close time.busy=85.9ms time.idle=26.1µs 2024-11-23T19:30:59.390922Z ERROR Ib_rs::service::search: Error building search index: LbErr { kind: AccountNonexistent, backtrace: Some(Backtrace [{ fn: "_ZL15_pthread_startPv"}, { fn: "start_thread" }])} 2024-11-23T19:31:24.857960Z DEBUG import_account{api_url=None}: Ib_rs::service::account: new 2024-11-23T19:31:24.859484Z ERROR import_account{api_url=None}: lb_rs::service::account: error=LbErr { kind: AccountStringCorrupted, backtrace: Some(Backtrace [])} 2024-11-23T19:31:24.859841Z DEBUG import_account{api_url=None}: Ib_rs::service::account: close time.busy=1.43ms time.idle=457μs 2024-11-23T19:31:26.294104Z DEBUG import_account{api_url=None}: Ib_rs::service::account: new 2024-11-23T19:31:26.295285Z ERROR import_account{api_url=None}: Ib_rs::service::account: error=LbErr { kind: AccountStringCorrupted, backtrace: Some(Backtrace []) } 2024-11-23T19:31:26.295634Z DEBUG import_account{api_url=None}: Ib_rs::service::account: close time.busy=1.34ms time.idle=191us 2024-11-23T19:31:27.067453Z DEBUG import_account{api_url=None}: Ib_rs::service::account: new 2024-11-23T19:31:27.069540Z ERROR import_account{api_url=None}: lb_rs::service::account: error=LbErr { kind: AccountStringCorrupted, backtrace: Some(Backtrace [])} 2024-11-23T19:31:27.070481Z DEBUG accountfan ervice
```

### PR DESCRIPTION
**Pull request by ad-tra**
fixes #3203

### CODE REVIEW

File: clients/android/app/src/main/java/app/lockbook/billing/BillingClientLifecycle.kt [hunk 1]
```diff
@@ -166,7 +166,9 @@ class BillingClientLifecycle private constructor(
             }
             billingResponse.isCancelable -> {}
             else -> {
-                _billingEvent.postValue(BillingEvent.NotifyErrorMsg(getString(applicationContext.resources, R.string.basic_error)))
+                if (billingResponse.code != BillingResponseClode.OK) {
```
Comment (smailbarkouch) [inline clients/android/app/src/main/java/app/lockbook/billing/BillingClientLifecycle.kt]: `BillingResponseClode`, mistype?

**Comment by smailbarkouch** [comment]
Don't think this is the right path - not super familiar what's going on here, but would investigate as to why this function is being called despite not having a purchase

**Comment by ad-tra** [comment]
> Don't think this is the right path - not super familiar what's going on here, but would investigate as to why this function is being called despite not having a purchase

`onQueryPurchasesResponse` is triggered in response to a query from the Google Play Billing Library for existing purchases made by the user. If you're a premium user then you've made a purchase in the past but if you haven't it's still called but with a purchase size of `0`.

**Comment by ad-tra** [comment]
I'm gonna merge this, but i'll keep an eye from any further billing bugs

**Comment by smailbarkouch** [comment]
> onQueryPurchasesResponse is triggered in response to a query from the Google Play Billing Library for existing purchases made by the user. If you're a premium user then you've made a purchase in the past but if you haven't it's still called but with a purchase size of 0.

Sounds good!
