### PR TITLE
ios: fix sidebar and landscape issues

### LINKED ISSUE #3791: iOS landscape looks busted
there's the obvious visual artifact captured here:

https://github.com/user-attachments/assets/45df6153-cd99-475e-9fce-4eb5ac2ac21c

the weirdest part is that you can't even drag from the left most part of the screen. there's probably some drag sone that needs to support negative values or something.

### PR DESCRIPTION
**Pull request by smailbarkouch**
This PR fixes the sidebar offset and landscape issues. 

fixes #3791

### CODE REVIEW

File: clients/apple/Shared/State/HomeState.swift [hunk 1]
```diff
@@ -51,10 +51,6 @@ class HomeState: ObservableObject {
         self.workspaceOutput = workspaceOutput
         self.filesModel = filesModel
         
-        #if os(iOS)
-        expandSidebarIfNoDocs()
-        #endif
```
Comment (smailbarkouch) [inline clients/apple/Shared/State/HomeState.swift:56]: Logic not needed now that sidebarState is a direct function of state
