### PR TITLE
apple: fix selected folder logic

### LINKED ISSUE #3922: opening a folder from the search files dialog doesn't expand the folder in the file tree

### PR DESCRIPTION
**Pull request by Parth**
fixes #3922

### CODE REVIEW

File: libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/macMTK.swift [hunk 1]
```diff
@@ -289,7 +289,17 @@ public class MacMTK: MTKView, MTKViewDelegate {
         dark_mode(wsHandle, isDarkMode())
         set_scale(wsHandle, scale)
         let output = macos_frame(wsHandle)
-
+        
+        if output.selected_folder_changed {
```
Comment (Parth) [inline libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/macMTK.swift:293]: this needs to happen in iOSMTK too
